version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"